services:
  caddy:
    image: docker.io/caddy:alpine
    container_name: caddy
    restart: unless-stopped
    extra_hosts:
      - mcp-playground:0.0.0.0
    networks:
      - reverse_proxy
    ports:
      - 8888:80
    volumes:
      - type: bind
        source: ./caddy/config
        target: /etc/caddy
        options: [z]

  contex7:
    image: "docker.io/mcp/context7:latest"
    container_name: context7
    networks:
      - reverse_proxy
    depends_on:
      - caddy

  sequentialthinking:
    image: "docker.io/supercorp/supergateway:latest"
    container_name: sequentialthinking
    command: >
      --stdio "npx -y @modelcontextprotocol/server-sequential-thinking"
    networks:
      - reverse_proxy
    depends_on:
      - caddy

networks:
  reverse_proxy:
