supergateway: &supergateway
  image: "docker.io/supercorp/supergateway:latest"
  networks:
    - reverse_proxy
  depends_on:
    - caddy

services:
  caddy:
    image: docker.io/caddy:alpine
    container_name: caddy
    networks:
      - reverse_proxy
    ports:
      - 8888:80
    volumes:
      - ./caddy/config:/etc/caddy:Z

  context7:
    image: "docker.io/mcp/context7:latest"
    container_name: context7
    networks:
      - reverse_proxy
    depends_on:
      - caddy

  github:
    <<: *supergateway
    container_name: github
    command: >
      --stdio 'npx -y @modelcontextprotocol/server-github' --baseUrl /github
    environment:
      GITHUB_TOOLSETS: ${GITHUB_TOOLSETS}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      GITHUB_READ_ONLY: ${GITHUB_READ_ONLY}

  sequentialthinking:
    <<: *supergateway
    container_name: sequentialthinking
    command: >
      --stdio 'npx -y @modelcontextprotocol/server-sequential-thinking@latest' --baseUrl /sequentialthinking

  terraform:
    image: docker.io/hashicorp/terraform-mcp-server:latest
    container_name: terraform
    command: >
      terraform-mcp-server streamable-http --transport-host 0.0.0.0
    networks:
      - reverse_proxy
    depends_on:
      - caddy

networks:
  reverse_proxy:
